[project]
name = "habits-tracker"
version = "0.1.0"
description = "Habits tracker API"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "asyncpg>=0.30.0",
    "httpx>=0.28.0",
    "bcrypt>=4.0.0",
    "email-validator>=2.2.0",
    "fastapi[standard]>=0.115.0",
    "pydantic-settings>=2.7.0",
    "pydantic[email-validator]>=2.10.0",
    "python-jose[cryptography]>=3.3.0",
    "python-multipart>=0.0.18",
    "sqlalchemy[asyncio]>=2.0.36",
]

[dependency-groups]
dev = [
    "aiosqlite>=0.20.0",
    "httpx>=0.28.0",
    "pytest>=8.3.0",
    "pytest-asyncio>=0.25.0",
]
