[pytest]
asyncio_mode = auto
markers =
    security: security-related tests
    integration: external interaction dependencies tests
    unit: unit tests
    user: user domain tests
    activity: activity domain tests
    expense: expense domain tests
    event: event domain tests
    entry: entry domain tests
    core: core domain tests